Repository MLH-Fellowship/project-a-m, pull requests merged in 2022-06, with the labels that each got.

#2 Feat/add issue templates
  .github/ISSUE_TEMPLATE/bug_report.yaml
  .github/ISSUE_TEMPLATE/feature_request.yaml
  .github/PULL_REQUEST_TEMPLATE.md
Labels: enhancement

#3 feat/refactor-project
  .github/ISSUE_TEMPLATE/config.yaml
  .gitignore
  .vscode/extensions.json
  README.md
  app/__init__.py
  app/static/img/favicon.ico
  app/static/img/logo.jpg
  app/static/img/logo.svg
  app/static/styles/main.css
  app/templates/index.html
  client/.npmrc
  client/README.md
  client/package.json
  client/public/favicon.ico
  client/src/components/Card.astro
  client/src/layouts/Layout.astro
  client/src/pages/index.astro
  client/tsconfig.json
  client/yarn.lock
  server/README.md
  server/requirements.txt
  server/src/__init__.py
Labels: enhancement

#4 fix: proper-indents
  .github/ISSUE_TEMPLATE/bug_report.yaml
  .github/ISSUE_TEMPLATE/feature_request.yaml
Labels: bug

#10 feat!(client): remove astro client and flask
  .vscode/extensions.json
  client/.npmrc
  client/README.md
  client/package.json
  client/public/favicon.ico
  client/src/components/Card.astro
  client/src/layouts/Layout.astro
  client/src/pages/index.astro
  client/tsconfig.json
  client/yarn.lock
  server/README.md
  server/requirements.txt
  server/src/__init__.py
Labels: enhancement

#13 feat: add header to page
  app/__init__.py
  app/static/styles/global.css
  app/templates/blocks/header.html
  app/templates/layout/base.html
Labels: enhancement

#16 docs: fix documentation
  .gitignore
  README.md
Labels: documentation

#15 feat/setup linting
  .editorconfig
  .gitignore
  .pylintrc
  .vscode/extensions.json
  .vscode/settings.json
  requirements.txt
Labels: enhancement

#18 feature: implemented footer
  app/__init__.py
  app/static/styles/global.css
  app/templates/blocks/footer.html
  app/templates/layout/base.html
Labels: enhancement

#20 feat/style content
  app/__init__.py
  app/static/styles/global.css
  app/templates/blocks/footer.html
  app/templates/blocks/header.html
  app/templates/pages/home.html
Labels: enhancement

#22 fix: back to top button
  app/templates/blocks/footer.html
Labels: bug

#24 fix: footer styling
  app/static/styles/global.css
  app/templates/blocks/footer.html
Labels: bug

#30 feat: add hobbies
  app/static/styles/global.css
  app/templates/pages/home.html
Labels: enhancement

#34 refactor: use loops for links
  app/templates/blocks/footer.html
  app/templates/blocks/header.html
  app/templates/layout/base.html
Labels: enhancement

#36 feat: add project page
  app/__init__.py
  app/static/project-template.md
  app/static/styles/global.css
  app/templates/blocks/header.html
  app/templates/layout/base.html
  app/templates/pages/project.html
Labels: enhancement

#37 feat: dynamic data
  .vscode/settings.json
  app/__init__.py
  app/static/styles/global.css
  app/static/user-template.json
  app/templates/blocks/hobby.html
  app/templates/pages/home.html
  app/utilities.py
Labels: enhancement

#38 fix: header nav
  app/templates/blocks/header.html
  app/templates/pages/home.html
Labels: bug

#39 fix: add requirements
  requirements.txt
Labels: bug

#41 Create LICENSE
  LICENSE
Labels: documentation

#42 feat: style additions
  app/static/styles/global.css
  app/static/user-template.json
  app/templates/blocks/project.html
  app/templates/layout/base.html
Labels: enhancement
